### ISSUE TITLE
引数の参照方法について

### ISSUE THREAD

**Issue by kwaka1208** [okhiroyuki/BlocklyDuino#14]
引数付きの関数を使った時、関数内部で引数を参照するにはどのブロックを使えばいいですか？

**Comment by okhiroyuki** [comment]
引数付き関数は、☆マークで引数を作ると、自動的に変数を追加しているので、それが使えると思います。
写真は戻り値付きですが、戻り値なしも同じです。

![blocklyduino](https://cloud.githubusercontent.com/assets/23309/13898570/df282e04-ee18-11e5-91e8-f4ef6ac9e3c5.png)

あと、日本語がおかしいことに気づいたので、修正しますorz

**Comment by kwaka1208** [comment]
変数が増えているのを確認しました。
あと、前に見つけた問題があったのを思い出しましたので、別チケット切ります。
