### ISSUE TITLE
◯◯秒待つで変数による指定ができない

### ISSUE THREAD

**Issue by kwaka1208** [okhiroyuki/BlocklyDuino#16]
これ、だいぶ前にも話題になったことがあると思います。
◯◯秒待つで変数による指定ができないので、ちょっと使いづらいです。

**Comment by okhiroyuki** [comment]
待ち時間を変数指定に変更した

![blocklyduino](https://cloud.githubusercontent.com/assets/23309/13898825/d936b1d8-ee21-11e5-90fb-191c3614925b.png)
