### ISSUE TITLE
Arduinoコードが生成されない

### ISSUE THREAD

**Issue by kwaka1208** [okhiroyuki/BlocklyDuino#17]
Web版でプログラムを作り、「Arduino」タブに切り替えた時にコードが表示されていませんでした。何がおかしいか、見ていただけますでしょうか。
[blockduino.xml.zip](https://github.com/okhiroyuki/BlocklyDuino/files/180923/blockduino.xml.zip)

**Comment by okhiroyuki** [comment]
どうも、millsを追加すると下記のエラーコードを吐いてます。

`blockly_compressed.js:1883 Uncaught Expecting tuple from value block "millis".`

millsをどけると、うまくArduinoコードが生成されてます。
ちょっとソースを確認します。
