### ISSUE TITLE
引数付き関数で、引数の型がつかない。

### ISSUE THREAD

**Issue by kwaka1208** [okhiroyuki/BlocklyDuino#18]
引数の型を指定する方法もない？

**Comment by okhiroyuki** [comment]
たしかに、型がない！
調べます。

**Comment by okhiroyuki** [comment]
下記でも議論されてますね。
基本的に、Globalで定義されるから、型指定はなくてもいいよーって感じなんですね。

https://github.com/BlocklyDuino/BlocklyDuino/issues/69
