### ISSUE TITLE
戻り値付き関数の型が、Dynamicになる。

### ISSUE THREAD

**Issue by kwaka1208** [okhiroyuki/BlocklyDuino#19]
戻り値付き関数の型が、Dynamicという型になる。

**Comment by okhiroyuki** [comment]
なんだろう、Dynamicって（笑）
修正します！

**Comment by okhiroyuki** [comment]
@6b0893d
Blockyはその特徴として、変数はすべてGlobalに扱ってます。
戻り値付き関数は、その特徴を汲み取ると、あまり意味のないものとなるため、一旦使用不可としました。
