### ISSUE TITLE
RGB LED Blockでうまく色が合わない

### ISSUE THREAD

**Issue by okhiroyuki** [okhiroyuki/BlocklyDuino#24]
# 概要

RGB LEDの初期化ブロックで書きだされたコードの一部、GRBをRGBに変えないと指定した通りの色にならないものがある。

```
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(1,2,NEO_GRB + NEO_KHZ800);
```
# 駄目だったパーツ

秋月電子で購入した WS2811 5mm Diff Lens と  NeoPixcel 8mm

**Comment by okhiroyuki** [comment]
# 原因

LED内部のチップによる違いがある模様。
（参考：https://github.com/adafruit/Adafruit_NeoPixel/blob/master/examples/strandtest/strandtest.ino）

``` c
// Parameter 1 = number of pixels in strip
// Parameter 2 = Arduino pin number (most are valid)
// Parameter 3 = pixel type flags, add together as needed:
//   NEO_KHZ800  800 KHz bitstream (most NeoPixel products w/WS2812 LEDs)
//   NEO_KHZ400  400 KHz (classic 'v1' (not v2) FLORA pixels, WS2811 drivers)
//   NEO_GRB     Pixels are wired for GRB bitstream (most NeoPixel products)
//   NEO_RGB     Pixels are wired for RGB bitstream (v1 FLORA pixels, not v2)
//   NEO_RGBW    Pixels are wired for RGBW bitstream (NeoPixel RGBW products)
```

**Comment by okhiroyuki** [comment]
# 対策

RGBLED blockの初期化部分に、チップの選択を入れると、より複雑となるため、 NeoPixel Blockを別途作成する方向としたい。

## RGBLED

WS2811というふうに補足しておく。
<img width="661" alt="blocklyduino" src="https://cloud.githubusercontent.com/assets/23309/15991061/6b3e94bc-30e2-11e6-89d1-0b4b66759fa9.png">

## Neopixel

<img width="669" alt="blocklyduino" src="https://cloud.githubusercontent.com/assets/23309/15991058/64ecbeea-30e2-11e6-9dc5-a1bfd96cbfd7.png">

**Comment by iwasa183** [comment]
早速のご対応に心から感謝申し上げます。
このように修正していただけると本当にありがたいです！
よろしくお願い申し上げます。

**Comment by okhiroyuki** [comment]
では、この形でアップデートいたします！

今後も、何かありましたら、ぜひこちらのIssueに投稿してくださいm(__)m

**Comment by okhiroyuki** [comment]
@2e7dc11 add neopixel blocks
